recette/accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),    
)

recette/kitchen/urls.py
from django.conf.urls import patterns, url
from kitchen import views

urlpatterns = patterns('',
    url(r'^$', views.userKitchen,name='index'),
    url(r'^createIngredient/',views.createIngredient,name='createIngredient'),
    url(r'^success/',views.success,name='success'),
    url(r'^addIngredientAmount/',views.addIngredientAmount,name='addIngredientAmount'),
    url(r'^addNewIngredient/',views.addNewIngredient,name='addNewIngredient')
)

recette/recette/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from homepage import views as hpViews


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'recette.views.home', name='home'),
    # url(r'^recette/', include('recette.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
	url(r'^kitchen/', include('kitchen.urls', namespace='kitchen')),
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
        url(r'^admin/', include(admin.site.urls)),
	url(r'^$', hpViews.index, name='index'),
)

recette/accounts/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

recette/homepage/models.py
from django.db import models

# Create your models here.

recette/kitchen/models.py
from django.db import models
from django.contrib.auth.models import User

class Ingredient(models.Model):
	name = models.CharField(max_length=128)
	basic_measure = models.CharField(max_length=32)
	ingredientType = models.CharField(max_length=32)
	brand = models.CharField(max_length=128)
	defaultAmount = models.PositiveIntegerField()

	def __unicode__(self):
		return self.name
	
		
class Kitchen(models.Model):
	user = models.ForeignKey(User)
	ingredients = models.ManyToManyField(Ingredient, through='KitchenIngredientList')
	
	def __unicode__(self):
		return 'Kitchen of ' + self.user.username
	
	
class KitchenIngredientList(models.Model):
	ingredient = models.ForeignKey(Ingredient)
	kitchen = models.ForeignKey(Kitchen)
	amount = models.PositiveIntegerField()

	def __unicode__(self):
		return 'Ingredients owned by ' + self.kitchen.user.username

recette/accounts/views.py
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Context, loader, RequestContext
from django.contrib.auth import authenticate, login as login_django, logout as logout_django
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, render_to_response
from django.core.context_processors import csrf
from django.views.decorators.csrf import requires_csrf_token

@requires_csrf_token
def register(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			return HttpResponseRedirect('/')
	else:
		form = UserCreationForm()
	return render(request, 'accounts/register.html', {
		'form': form
	})
	
def login(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username = username, password = password)
		if user is not None:
			login_django(request, user)
			return HttpResponseRedirect('/')
		else:
			return HttpResponse('Invalid login information.')
	else:
		context = {}
		context.update(csrf(request))
		return render_to_response('accounts/login.html', context)
		
def logout(request):
	logout_django(request)
	return HttpResponseRedirect('/')

	

recette/dinner/views.py
# Create your views here.

recette/homepage/views.py
from django.template import RequestContext
from django.shortcuts import render, render_to_response

def index(request):
	context = RequestContext(request, {})
	return render_to_response('homepage/base.html', context)

recette/kitchen/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.core.context_processors import csrf
from django.views.decorators.csrf import csrf_protect
from django import forms
from django.utils import simplejson
import kitchenAPI


@login_required
@csrf_protect

def userKitchen(request):
	ingredientList = kitchenAPI.getKitchenIngredientList(request.user)
	context = RequestContext(request, {
		'all_ingredient_list': kitchenAPI.getKitchenIngredientList(request.user),
		'user':request.user,
		'all_ingredient_Names': kitchenAPI.getAllIngredientNames(),
	})
	return render_to_response('kitchen/userKitchen.html', context)

class CreateIngredientForm(forms.Form):
     ingredientName = forms.CharField()
     ingredientType = forms.CharField()
     basicMeasure = forms.CharField()
     brand = forms.CharField()
     defaultAmount = forms.FloatField()

def createIngredient(request):
	if request.method == 'GET':
		context = RequestContext(request, {
				'user':request.user,
		})
		return render_to_response('kitchen/createIngredient.html',context)
	if request.method == 'POST':
		ciForm = CreateIngredientForm(request.POST)
		if ciForm.is_valid():
			print "valid form"
			kitchenAPI.createIngredient(ciForm.cleaned_data['ingredientName'],
					 ciForm.cleaned_data['basicMeasure'],
					 ciForm.cleaned_data['ingredientType'],
					 ciForm.cleaned_data['brand'],
					 int(ciForm.cleaned_data['defaultAmount']*100))
			return HttpResponseRedirect('seccess/') 

def success(request):
	return HttpResponse("seccess")

def addIngredientAmount(request):
	if request.is_ajax():
		print('AJAX!!!')
		if request.method == 'POST':
			print request.body
			print "PRINT...."
			json_data = simplejson.loads(request.body)
			try:
				print json_data['ingredientID']
				print json_data['amountAdd']
				kitchenAPI.increaseIngredientAmount(currentUser = request.user,ingredientID = json_data['ingredientID'],amount = int(float(json_data['amountAdd'])*100))
			except KeyError:
				HttpResponseServerError("Malformed data!")
	return HttpResponseRedirect('/kitchen/')

def addNewIngredient(request):
	if request.is_ajax():
		print('AJAX!!!')
		if request.method == 'POST':
			print request.body
			print "PRINT...."
			json_data = simplejson.loads(request.body)
			try:
				print json_data['ingredientName']
				print json_data['amount']
				kitchenAPI.addIngredient(currentUser = request.user,ingredientName = json_data['ingredientName'],amount = int(float(json_data['amount'])*100))
			except KeyError:
				HttpResponseServerError("Malformed data!")
	return HttpResponseRedirect('/kitchen/')

recette/recipe/views.py
# Create your views here.

recette/accounts/templates/accounts/login.html
<h3>Login page</h3>

<form action="{% url 'accounts:login' %}" method="post">
{% csrf_token %}
	<input type="text" name="username" placeholder="Your username"/>
	<input type="text" name="password" placeholder="Your password"/>
	<input type="submit" value="Login" />
</form>

recette/accounts/templates/accounts/register.html
{% block title %}Create an account{% endblock %}

{% block content %}
  <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Create the account">
  </form>
{% endblock %}

recette/homepage/templates/homepage/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Recette{% endblock %}</title>
    <script type="text/javascript" src= "/static/jQuery/jquery-2.0.3.js"></script>
</head>

<body>

	<div id="topbar">
		<div class="navbar">
			<div class="navbar-side navbar-left"></div>
			<div class="navbar-content">
			  {% if user.is_authenticated %}
				<span>Welcome, {{ user.username }}</span>         	        	
				<a href="{% url 'accounts:logout' %}">Logout</a>
			  {% else %}
				<span>Welcome, </span>         	
				<a href="{% url 'accounts:login' %}">Login</a> or
				<a href="{% url 'accounts:register' %}">Sign up</a>
			  {% endif %}
			</div>
			<div class="navbar-side navbar-right"></div>
		</div>
	</div>

    <div id="content">
        {% block content %}Oops...you have wandered into an undefined area.{% endblock %}
    </div>
</body>
</html>

recette/kitchen/templates/kitchen/createIngredient.html
{% extends "homepage/base.html" %}

{% block content %}
   <form action = "." method = "post">{% csrf_token %}
     Ingredient name: <input type="text" name="ingredientName"><br>
     Ingredient type: <input type="text" name="ingredientType"><br>
     basic measure:<input type="text" name="basicMeasure"><br>
     brand: <input type="text" name="brand"><br>
     default amount:<input type="text" name="defaultAmount"><br>
     <input type="submit" value="Submit">
   </form> 
{% endblock %}

recette/kitchen/templates/kitchen/userKitchen.html
{% extends "homepage/base.html" %}

{% block title %}
  Tasks
{% endblock %}

{% block content %}
  <script type = "text/javascript">
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');
  function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
      crossDomain: false, // obviates need for sameOrigin test
      beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type)) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
      }
  });    
  function addIngredientAmount(ingredientID){
      $.post(location.href+"addIngredientAmount/",
        JSON.stringify({
          "ingredientID":ingredientID,
          "amountAdd":$("#amountInput"+ingredientID).val()
        }),function(data){
           location.reload()
        }
      ).fail(function() { alert("error"); })
    }
    function stopPosting(e,ingredientID){
      e.preventDefault();
      addIngredientAmount(ingredientID);
      return false;
    }

    function addNewIngredient(e){
       e.preventDefault();
       $.post(location.href+"addNewIngredient/",
        JSON.stringify({
          "ingredientName":$("#ingredientSelector").val(),
          "amount":$("#amountInputNewIngredient").val()
        }),function(data){
           location.reload()
        }
      ).fail(function() { alert("error"); })      
    }
  </script>
  <p>This is {{ user.username }} 's kitchen.</p>

  {% if all_ingredient_list %}
    <ul>
      {% for ingredient,amount in all_ingredient_list %}
      <p><form onSubmit="stopPosting(event,{{ingredient.pk}});">  {{ ingredient.name }} {{amount}} {{ingredient.basic_measure}}+<input type = "text" id = "amountInput{{ingredient.pk}}"><input type = "submit" value = "add"></form></p>
      {% endfor %}
    </ul>
    {% else %}
    <p>No ingredients are available.</p>
  {% endif %}
    <form onSubmit="addNewIngredient(event);">
      add 
      <select id = "ingredientSelector">
	<option value="" disabled="disabled" selected="selected">Please select a ingredient</option>
	{% for ingredientName in all_ingredient_Names%}
	<option value="{{ingredientName}}">{{ingredientName}}</option>
	{% endfor %}
      </select>
      <input type = "text" id = "amountInputNewIngredient">
      <input type = "submit" value = "add">
    </form>
{% endblock %}